"""empty message

Revision ID: 66861334b7b4
Revises: 4c4f480ee36b
Create Date: 2022-08-19 11:13:40.913150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66861334b7b4'
down_revision = '4c4f480ee36b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.String(length=300), nullable=True))
    op.drop_column('Artist', 'website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###
